---

- name: ping router
  hosts: routers
  connection: local
  tasks:
  - name: Ping
    shell: ping -c 3 {{inventory_hostname}}
    register: result
  - debug:
     msg: "{{result.stdout_lines}}"
    when: result.rc == 0
